version: "3.9"
services:
  todo_app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./todo_app
        target: /todo_app/todo_app
  todo_app_test:
    build:
      context: .
      target: development
    env_file: ./.env.test
    volumes:
      - type: bind
        source: ./todo_app
        target: /todo_app/todo_app
      - type: bind
        source: ./tests
        target: /todo_app/tests
    entrypoint: watchmedo shell-command --patterns="*.py" --recursive --command "poetry run pytest"