version: "3.9"
services:
  todo_app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./todo_app
        target: /todo_app/todo_app